//

DROP TABLE IF EXISTS Employee;
CREATE TABLE Employee(ID INT PRIMARY KEY,NAME VARCHAR(255), DOB VARCHAR(255),QUALIFICATION VARCHAR(255),SALARY DOUBLE, ADDRESS VARCHAR(255));
INSERT INTO Employee VALUES(1, 'poonra','20-07-1988','MTECH',12000.00,'hyderabad');
SELECT * FROM Employee ;